config/routes.rb
Apollo::Application.routes.draw do
  resources :classification_releases

  resources :reports, :except => [:all] do
    collection do
      get "account_statement"
      get "dentist_statement"
      get "receipt"
    end
  end
  resources :financial_releases do
    collection do
      get "payment"
      get "transfer_values"
      get "dentist_open_values"
      put "update_dentist_values"
    end
  end

  resources :apportionments, :except => [:show]

  resources :accounts, :except => [:show]

  resources :type_procedures, :except => [:show]

  resources :dentists, :except => [:show]

  root "home#index"
  devise_for :users, :path_prefix => 'my'
  resources :users

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @accounts = Account.where("organization_id = ? and account_type = 2", current_user.organization_id)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% content_for :head do %>
<h2>Início</h2>
<% end %>

<div class="row">
  <div class="span8">
    <div class="row">
      <h3>Movimentações</h3>
      <hr>
      <%= link_to "Nova entrada", new_financial_release_path(type_release: 1), class: "btn btn-default btn-large"%>
      <%= link_to "Nova saída", new_financial_release_path(type_release: 2), class: "btn btn-default btn-large"%>
      <%= link_to "Repasse ao dentista", transfer_values_financial_releases_path, class: "btn btn-default btn-large"%>
    </div>
    <br>
    <div class="row">
      <h3>Extratos</h3>
      <hr>
      <%= link_to "Extrato da conta", account_statement_reports_path , class: "btn btn-default btn-large"%>
      <%= link_to "Extrato do dentista", dentist_statement_reports_path , class: "btn btn-default btn-large"%>
    </div>
    <br>
    <div class="row">
      <h3>Saldos dos dentistas</h3>
      <hr>
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>Descrição</th>
            <th>Valor</th>
          </tr>
        </thead>
        <tbody>
          <% @accounts.each do |account|%>
            <tr>
              <td><%= account.name %></td>
              <td><%= account.localized.balance %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
  <div class="span4">
    <h3>Registrar recebimento do paciente</h3>
    <hr>
    <%= render "financial_releases/form_receipt"%>
  </div>
</div>