config/routes.rb
Apollo::Application.routes.draw do
  resources :classification_releases

  resources :reports, :except => [:all] do
    collection do
      get "account_statement"
      get "dentist_statement"
      get "receipt"
    end
  end
  resources :financial_releases do
    collection do
      get "payment"
      get "transfer_values"
      get "dentist_open_values"
      put "update_dentist_values"
    end
  end

  resources :apportionments, :except => [:show]

  resources :accounts, :except => [:show]

  resources :type_procedures, :except => [:show]

  resources :dentists, :except => [:show]

  root "home#index"
  devise_for :users, :path_prefix => 'my'
  resources :users

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def account_statement
    @releases = []
    if params[:account] && params[:start_date] && params[:end_date]
      start_date = DateTime.strptime(params[:start_date], "%d/%m/%Y")
      end_date = DateTime.strptime(params[:end_date], "%d/%m/%Y")
      @prior_balance, @releases, @final_balance = FinancialRelease.account_statement(params[:account], start_date, end_date)
    end
  end

  def dentist_statement
    @releases = []
    if params[:account] && params[:start_date] && params[:end_date]
      start_date = DateTime.strptime(params[:start_date], "%d/%m/%Y")
      end_date = DateTime.strptime(params[:end_date], "%d/%m/%Y")
      @prior_balance, @releases, @final_balance = FinancialRelease.account_statement(params[:account], start_date, end_date)
    end
  end

  def receipt
    @financial_release = FinancialRelease.find(params[:id])
    @dentist = Dentist.where("account_id = ?", @financial_release.account_id)
    respond_to do |format|
      format.pdf do
        render :pdf => "recibo", :template => "reports/receipt.pdf.erb"
      end
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/account_statement.html.erb
<%= render "layouts/head", title: "Extrado simples", description: ""%>

<%= form_tag account_statement_reports_path, method: :get, class: "well form-inline" do %>
  <label>Conta: </label>
  <%= select_tag :account, options_from_collection_for_select(accounts_by_organization, "id", "name", params[:account]) %>
  <label>Período: </label>
  <%= text_field_tag :start_date, params[:start_date], class:"date_string"%>
  <%= text_field_tag :end_date, params[:end_date], class:"date_string"%>
  <%= submit_tag "Filtrar", class: "btn btn-primary"%>
<% end %>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Data</th>
      <th>Descrição</th>
      <th>Tipo</th>
      <th>Valor</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td></td>
      <td>Saldo Anterior</td>
      <td></td>
      <td class="statement-number"><%= number_with_precision(@prior_balance)%></td>
    </tr>
    <% @releases.each do |release| %>
      <% present release do |financial_release_presenter| %>
      <tr>
        <td><%= financial_release_presenter.date_formatted %></td>
        <td><%= financial_release_presenter.description %></td>
        <td><%= financial_release_presenter.type_release %></td>
        <td class="statement-number"><%= financial_release_presenter.value_formatted %></td>
      </tr>
      <% end %>
    <% end %>
    <tr>
      <td></td>
      <td>Saldo Final</td>
      <td></td>
      <td class="statement-number"><%= number_with_precision(@final_balance) %></td>
    </tr>
  </tbody>
</table>

<script>
  $(".date").mask("99/99/9999");
  $('.value').priceFormat({
    prefix: '',
    centsSeparator: ',',
    thousandsSeparator: '.',
    limit: 8,
    centsLimit:2
  });
</script>

app/views/reports/dentist_statement.html.erb
<%= render "layouts/head", title: "Extrado simples", description: ""%>

<%= form_tag dentist_statement_reports_path, method: :get, class: "well form-inline" do %>
  <label>Conta: </label>
  <%= select_tag :account, options_from_collection_for_select(accounts_dentists_by_organization, "id", "name", params[:account]) %>
  <label>Período: </label>
  <%= text_field_tag :start_date, params[:start_date], class:"date_string"%>
  <%= text_field_tag :end_date, params[:end_date], class:"date_string"%>
  <%= submit_tag "Filtrar", class: "btn btn-primary"%>
<% end %>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Data</th>
      <th>Descrição</th>
      <th>Tipo</th>
      <th>Valor</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td></td>
      <td>Saldo Anterior</td>
      <td></td>
      <td><%= @prior_balance%></td>
    </tr>
    <% @releases.each do |release| %>
      <% present release do |financial_release_presenter| %>
      <tr>
        <td><%= financial_release_presenter.date_formatted %></td>
        <td><%= financial_release_presenter.description %></td>
        <td><%= financial_release_presenter.type_release %></td>
        <td><%= financial_release_presenter.value_formatted %></td>
      </tr>
      <% end %>
    <% end %>
    <tr>
      <td></td>
      <td>Saldo Final</td>
      <td></td>
      <td><%= @final_balance %></td>
    </tr>
  </tbody>
</table>

<%= link_to "Efetuar pagamento", payment_financial_releases_path(account_id: params[:account]), class: "btn btn-primary btn-large"%>

<script>
  $(".date").mask("99/99/9999");
  $('.value').priceFormat({
    prefix: '',
    centsSeparator: ',',
    thousandsSeparator: '.',
    limit: 8,
    centsLimit:2
  });
</script>

app/views/reports/receipt.pdf.erb
<h4> RECIBO DE PAGAMENTO</h4>
Dentista: <%= @dentist.name %>
Data do pagamento: <%= @financial_release.localized.release_date %>