config/routes.rb
Apollo::Application.routes.draw do
  resources :classification_releases

  resources :reports, :except => [:all] do
    collection do
      get "account_statement"
      get "dentist_statement"
      get "receipt"
    end
  end
  resources :financial_releases do
    collection do
      get "payment"
      get "transfer_values"
      get "dentist_open_values"
      put "update_dentist_values"
    end
  end

  resources :apportionments, :except => [:show]

  resources :accounts, :except => [:show]

  resources :type_procedures, :except => [:show]

  resources :dentists, :except => [:show]

  root "home#index"
  devise_for :users, :path_prefix => 'my'
  resources :users

end

app/views/layouts/_head.html.erb
<%= content_for :head do %>
<h2><%= title if defined? title %></h2>
<p><%= description if  defined? description %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Apollo</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,600,800">
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application"%>
  </body>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="wrapper">
  <div id="topbar">
    <div class="container">
      <div id="top-nav">
        <ul class="pull-right">
          <li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
    </div>
  </div>
  <div id="header">
    <div class="container">
      <a href="#" class="brand">Apollo</a>
      <div class="nav-collapse">
        <ul id="main-nav" class="nav pull-right">
          <li class="nav-icon <%= controller.controller_path == 'home' ? 'active' : '' %>">
            <%= link_to root_path do%>
              <i class="fa fa-home"></i>
              <span>Início</span>
            <% end %>
          </li>
          <li class="dropdown <%= (controller.controller_path == 'dentists' || controller.controller_path == 'type_procedures' || controller.controller_path == 'accounts' || controller.controller_path == 'classification_releases') ? 'active' : '' %>">
            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-list"></i>
              <span>Cadastros</span>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Contas", accounts_path %></li>
              <li><%= link_to "Dentistas", dentists_path %></li>
              <li><%= link_to "Rateio", apportionments_path %></li>
              <li><%= link_to "Tipos de procedimento", type_procedures_path %></li>
              <li><%= link_to "Classificação de lançamentos", classification_releases_path %></li>
              <li><%= link_to "Usuários", users_path %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div id="masthead">
    <div class="container">
      <div class="masthead-pad">
        <div class="masthead-text">
          <%= yield :head%>
        </div>
      </div>
    </div>
  </div>
  <div id="content">
    <div class="container">
      <div id="notice" style="<%= 'display:none' unless flash[:notice] %>" class="alert alert-success fade in" data-alert="alert">
        <a class="close" data-dismiss='alert' href="#">×</a>
        <p><%= flash[:notice] %></p>
      </div>
      <%= yield %>
    </div>
  </div>
</div>
<div id="footer">
  <div class="container">
    <div class="row">
      <div class="span6">
        © 2014 <a href="http://www.itium.com.br">Itium</a>, Todos os direitos reservados.
      </div>
      <div id="builtby" class="span6">
        <a href="http://www.itium.com.br">Desenvolvido por Itium Tecnologia.</a>
      </div>
    </div>
  </div>
</div>

</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Apollo</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="login">
  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: "alert alert-#{name}" if msg.is_a?(String) %>
  <% end %>
  <%= yield %>
</body>