config/routes.rb
Apollo::Application.routes.draw do
  resources :classification_releases

  resources :reports, :except => [:all] do
    collection do
      get "account_statement"
      get "dentist_statement"
      get "receipt"
    end
  end
  resources :financial_releases do
    collection do
      get "payment"
      get "transfer_values"
      get "dentist_open_values"
      put "update_dentist_values"
    end
  end

  resources :apportionments, :except => [:show]

  resources :accounts, :except => [:show]

  resources :type_procedures, :except => [:show]

  resources :dentists, :except => [:show]

  root "home#index"
  devise_for :users, :path_prefix => 'my'
  resources :users

end

app/models/account.rb
class Account < ActiveRecord::Base
  include I18n::Alchemy
  localize :balance, :using => :number
  before_create :set_account_type
  default_scope order("name ASC")
  scope :by_organization, lambda { |organization_id| where(organization_id: organization_id) }

  validates_presence_of :name

  def self.update_balance(account_id, value)
    account = Account.where("id = ?", account_id).first
    account.balance += value
    account.save
  end

  def set_account_type
    self.account_type = 1 if self.account_type.nil?
  end
end

app/controllers/accounts_controller.rb
class AccountsController < InheritedResources::Base
  actions :all, :except => [:show]
  
  has_scope :by_organization
  
  def collection
    @accounts ||= end_of_association_chain.paginate(:page => params[:page])
  end
  
  def permitted_params
    params.permit(:account => [:name])
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= simple_form_for(@account) do |f| %>
<fieldset>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
</fieldset>
<% end %>

app/views/accounts/edit.html.erb
<%= render "layouts/head", title: "Contas", description: "Alterar dados da conta"%>

<%= link_to accounts_path, class: "btn btn-default" do %>
  <i class="fa fa-reply"></i> Voltar
<% end %>
<hr>


<%= render 'form' %>

app/views/accounts/index.html.erb
<%= render "layouts/head", title: "Contas", description: "Lista"%>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Saldo</th>
      <th class="last_column">Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.name %></td>
        <td><%= number_to_currency(account.balance, unit: "R$", separator: ",", delimiter: ".") %></td>
        <td>
          <%= link_to edit_account_path(account), class: "btn btn-default" do %>
            <i class="fa fa-edit"></i>
          <% end %>
          <%= link_to account, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" do %>
            <i class="fa fa-trash-o"></i>
          <% end %>
          <%= link_to financial_releases_path(by_account: account.id), class: "btn btn-default" do%>
            <i class="fa fa-list"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @accounts, renderer: BootstrapPagination::Rails %>
<br>

<%= link_to new_account_path, class: "btn btn-primary" do%>
  <i class="fa fa-plus"></i> Nova conta
<% end %>

app/views/accounts/new.html.erb
<%= render "layouts/head", title: "Contas", description: "Incluir nova conta"%>

<%= link_to accounts_path, class: "btn btn-default" do %>
  <i class="fa fa-reply"></i> Voltar
<% end %>
<hr>

<%= render 'form' %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>